package com.standingcat.event.model;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.persistence.*;
import lombok.*;

import java.util.HashSet;
import java.util.Set;

@Entity
@Table(name = "app_user")
@Data //getters, setters, equals, hashCode, toString generated by Lombok
@NoArgsConstructor
@AllArgsConstructor
public class User {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY) //strategy is automatic
    private Long id;

    @Column(unique = true, nullable = false)
    private String username;

    @Column(nullable = false)
    @JsonProperty(access = JsonProperty.Access.WRITE_ONLY)
    private String password;

    @Column(unique = true, nullable = false)
    private String email;

    @ElementCollection(fetch = FetchType.EAGER) //fetch roles eagerly
    @CollectionTable(name = "user_roles", joinColumns = @JoinColumn(name = "user_id")) //make a new table for this set
    @Column(name = "role")
    @JsonIgnore
    private Set<String> roles = new HashSet<>(); // e.g., "ROLE_USER", "ROLE_ADMIN"

    //for now, event creation is intended for admins
    //cascade type set to all, when a user is deleted so should all the created events
    //orphanRemoval set to true to automatically remove from the database an event deleted from the user
    @JsonIgnore // <— prevent Event -> owner -> createdEvents -> owner -> …
    @OneToMany(mappedBy = "owner", orphanRemoval = true)
    @ToString.Exclude
    @EqualsAndHashCode.Exclude
    private Set<Event> createdEvents = new HashSet<>();

    //might be confusing but conceptually, a User can enroll in many Events (Many-to-Many with Event)
    //implementation-wise though, a User has many Enrollment records (One-to-Many with Enrollment)
    //user can have multiple enrollments but an enrollment can only have one user
    @JsonIgnore // <— prevent Enrollment -> user -> enrollments -> event -> …
    @OneToMany(mappedBy = "user", orphanRemoval = true)
    @ToString.Exclude
    @EqualsAndHashCode.Exclude
    private Set<Enrollment> enrollments = new HashSet<>();

}
